---
- name: Downloading IBM Terraform Provider
  get_url:
    url: 'https://github.com/IBM-Cloud/terraform-provider-ibm/releases/download/v{{ IBM_Provider_version }}/terraform-provider-ibm_{{ IBM_Provider_version }}_linux_{{ Architecture }}.zip'
    dest: "{{ Provider_path }}"
    checksum: sha256:{{ LinuxSHA256SUMS }}

- name: Extract Terraform provider into {{ Provider_path }} 
  ansible.builtin.unarchive:
    src: '{{ Provider_path }}/terraform-provider-ibm_{{ IBM_Provider_version }}_linux_{{ Architecture }}.zip'
    dest: '{{ Provider_path }}/'
    copy: no

- name: Create Link Terrafrom to Plugin directory
  file:
    src: '{{ Provider_path }}/terraform-provider-ibm_v{{ IBM_Provider_version }}'
    dest: '{{ terraformPlugin }}/terraform-provider-ibm_v{{ IBM_Provider_version }}'
    state: link