driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  converge_sequence:
    # - dependency
    - create
    # - prepare
    - converge
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy

