driver:
  name: docker
platforms:
  - name: ibm_terraform_provider-test-${MOLECULE_DISTRO:-centos8}
    image: quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos8}-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  converge_sequence:
    # - dependency
    - create
    # - prepare
    - converge
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
